@Application_HostAddress = http://localhost:5024

GET {{Application_HostAddress}}/health

###

GET {{Application_HostAddress}}/events

###

POST {{Application_HostAddress}}/cart
Content-Type: application/json

{ "Name": "Shopping Cart 1" }

###

GET {{Application_HostAddress}}/cart/0434a9fc-8130-47bb-a0c7-f984b07cc6be

###

POST {{Application_HostAddress}}/cart/0434a9fc-8130-47bb-a0c7-f984b07cc6be/items
Content-Type: application/json

{ "Name": "Milk", "Quantity": 2 }

###
