# @host = http://0.0.0.0:80
@host = http://0.0.0.0:5002

###

GET {{host}}/events?startRange=1&endRange=10
Accept: application/json

###

POST {{host}}/specialoffers
Content-Type: application/json

{
    "Id": 1,
    "Description": "This is a special offer"
}

###

GET {{host}}/specialoffers/2
Accept: application/json


###

PUT {{host}}/specialoffers/2
Content-Type: application/json

{
    "Id": 2,
    "Description": "Other description"
}
