@LoyaltyProgram_HostAddress = http://localhost:5051

GET {{LoyaltyProgram_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LoyaltyProgram_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "name":"kyle",
  "loyaltyPoints": 0,
  "settings":{ "interests" : ["whisky", "cycling"] }
}

